# Practical Implemention of the  BiRNNs

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [2]:
from tensorflow.keras.datasets import imdb

max_features = 10000

(X_train, y_train), (X_test, y_test) = imdb.load_data(
    num_words=max_features
)

print("Training data shape:", X_train.shape)
print("Training labels shape:", y_train.shape)

print("Test data shape:", X_test.shape)
print("Test labels shape:", y_test.shape)

Training data shape: (25000,)
Training labels shape: (25000,)
Test data shape: (25000,)
Test labels shape: (25000,)


In [3]:
print(X_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [4]:
print(y_train[0])

1


In [5]:
word_index = imdb.get_word_index()

In [6]:
reverse_word_index = {
    value: key
    for (key, value) in word_index.items()
}

In [7]:
decoded_review = " ".join(
    reverse_word_index.get(i - 3, "?")
    for i in X_train[0]
)

print(decoded_review)

? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you thi

In [8]:
print(len(X_train[0]))

218


In [11]:
MAX_LEN = 200  # or 300, 500

In [12]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train = pad_sequences(
    X_train,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

X_test = pad_sequences(
    X_test,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

In [13]:
print("Training Shape :", X_train.shape)
print("Testing Shape  :", X_test.shape)

Training Shape : (25000, 200)
Testing Shape  : (25000, 200)


In [14]:
print("First Review Shape :", X_train[0].shape)
print("First Label :", y_train[0])

First Review Shape : (200,)
First Label : 1


In [16]:
from tensorflow.keras.layers import Bidirectional

In [17]:
VOCAB_SIZE = 10000
MAX_LEN = 200
EMBEDDING_DIM = 128
RNN_UNITS = 64

In [19]:
model = Sequential([
    Embedding(VOCAB_SIZE, EMBEDDING_DIM, input_length=MAX_LEN),

   Bidirectional(
        SimpleRNN(
            units=RNN_UNITS
        )
    ),


   Dense(64, activation="relu"),
   Dense(1, activation="sigmoid")

])


d:\Sequence-Models-BiRNN-Seq2Seq-Attention\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(
  optimizer="adam",
  loss="binary_crossentropy",
  metrics=["accuracy"]
)

In [22]:
history = model.fit(
  X_train,
  y_train,
  epochs=10,
  batch_size=32,
  validation_split=0.2
)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 29s 44ms/step - accuracy: 0.5436 - loss: 0.6876 - val_accuracy: 0.5522 - val_loss: 0.6896
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 29s 46ms/step - accuracy: 0.5814 - loss: 0.6731 - val_accuracy: 0.5660 - val_loss: 0.6806
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 34s 54ms/step - accuracy: 0.7103 - loss: 0.5603 - val_accuracy: 0.6722 - val_loss: 0.6080
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.6966 - loss: 0.5726 - val_accuracy: 0.5464 - val_loss: 0.7201
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 33s 53ms/step - accuracy: 0.6415 - loss: 0.6051 - val_accuracy: 0.5364 - val_loss: 0.7410
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 32s 51ms/step - accuracy: 0.6797 - loss: 0.5501 - val_accuracy: 0.5344 - val_loss: 0.7704
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 33s 52ms/step - accuracy: 0.6918 - loss: 0.5236 - val_accuracy: 0.5334 - val_loss: 0.8246
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 34s 54ms/step - accuracy: 0.7286 - loss: 0.4736 - 

In [23]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy:.4f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.5405 - loss: 1.1129
Test Loss     : 1.1129
Test Accuracy : 0.5405


In [24]:
predictions = model.predict(X_test)

print(predictions[:5])

782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 12ms/step
[[0.02185418]
 [0.84202826]
 [0.97051424]
 [0.46437734]
 [0.6187935 ]]


In [25]:
predicted_labels = (predictions > 0.5).astype(int)

print(predicted_labels[:5])

[[0]
 [1]
 [1]
 [0]
 [1]]


In [26]:
predicted_labels = (predictions > 0.5).astype(int)

print(predicted_labels[:5])

[[0]
 [1]
 [1]
 [0]
 [1]]


In [27]:
for i in range(5):
    print(f"Actual    : {y_test[i]}")
    print(f"Predicted : {predicted_labels[i][0]}")
    print("-" * 30)

Actual    : 0
Predicted : 0
------------------------------
Actual    : 1
Predicted : 1
------------------------------
Actual    : 1
Predicted : 1
------------------------------
Actual    : 0
Predicted : 0
------------------------------
Actual    : 1
Predicted : 1
------------------------------


In [28]:
model.save("birnn_imdb.keras")

# For a real-world implementation, consider replacing SimpleRNN with LSTM:

        from tensorflow.keras.layers import LSTM

        model = Sequential([
            Embedding(VOCAB_SIZE, EMBEDDING_DIM),

            Bidirectional(
                LSTM(64)
            ),

            Dense(64, activation="relu"),

            Dense(1, activation="sigmoid")
        ])

### A Bidirectional LSTM (BiLSTM) generally performs better on text classification because it handles long-term dependencies more effectively. For learning purposes, however, implementing BiRNN with SimpleRNN first is the right progression before moving on to BiLSTM and BiGRU.

In [29]:
import tensorflow as tf

model = tf.keras.models.load_model("birnn_imdb.keras")

In [30]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

782/782 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.5405 - loss: 1.1129
Test Loss: 1.1129
Test Accuracy: 0.5405


In [31]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predicted_labels))

              precision    recall  f1-score   support

           0       0.54      0.56      0.55     12500
           1       0.54      0.52      0.53     12500

    accuracy                           0.54     25000
   macro avg       0.54      0.54      0.54     25000
weighted avg       0.54      0.54      0.54     25000



In [33]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predicted_labels)

print(cm)

[[6968 5532]
 [5956 6544]]


In [35]:
from tensorflow.keras.datasets import imdb

word_index = imdb.get_word_index()

In [36]:
def encode_review(review):

    words = review.lower().split()

    encoded = []

    for word in words:
        if word in word_index:
            encoded.append(word_index[word] + 3)
        else:
            encoded.append(2)   # Unknown word

    return encoded

In [37]:
def predict_review(review):

    encoded_review = encode_review(review)

    padded_review = pad_sequences(
        [encoded_review],
        maxlen=MAX_LEN,
        padding="post",
        truncating="post"
    )

    prediction = model.predict(padded_review, verbose=0)[0][0]

    print(f"Review : {review}")
    print(f"Probability : {prediction:.4f}")

    if prediction >= 0.5:
        print("Prediction : Positive 😊")
    else:
        print("Prediction : Negative 😞")

In [38]:
predict_review("This movie was absolutely amazing and I loved every moment.")

Review : This movie was absolutely amazing and I loved every moment.
Probability : 0.5128
Prediction : Positive 😊


In [39]:
predict_review("The movie was boring and a complete waste of time.")

Review : The movie was boring and a complete waste of time.
Probability : 0.4561
Prediction : Negative 😞
